name: CI

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: login to heroku registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "logging in to heroku registry"
        heroku container:login
    - name: build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "build the image and push it to the heroku registry"
        heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web

  release:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "release the image to the heroku app"
          heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web

